(print "This is a test")
(print " | ")
(print (+ 3 5))
(print " | ")
(print '(a b c))
(print " | ")
(print (cdr '(a b c)))
(print " | ")
(print (car '(a b c)))
(print " | ")
(print (cons 'a '(b c)))
(print " | ")
(print true)
(print " | ")
(print false)
(print " | ")
(print (eq? 5 5))
(print " | ")
(print (eq? 3 5))
(print " | ")
(print (atom? 'a))
(print " | ")
(print (atom? '(1 2 3)))
;(print " | ")
